Add AvoidNegatedCollectionFilterOrRejectRector
driftingly/rector-laravel pull request #234
Opened 2024-07-16 15:07 UTC by spawnia

The test currently fails and I am not sure how to make it work.

```diff
 (new Collection([0, 1, null, -1]))
     ->reject(fn (?int $number): bool => is_null($number))
-    ->filter(fn (int $number): bool => $number > 0);
+    ->reject(fn (int $number): bool => ! ($number > 0));
```

I think there can be additional logic to simplify conditionals that use negated comparisons:

```diff
- ->filter(fn (int $n): bool => $n !== 0)
+ ->reject(fn (int $n): bool => $n === 0)
```

I also wonder where this rule would be included, perhaps in the code quality set list?

What do you think about this idea in general? Would you be up for inclusion?

2024-07-17 20:11 UTC, GeniJaho commented
@spawnia thanks for your PR. I think it would make a great addition to the Code Quality set. At first, it can be simple with just the negated expressions, not the negated comparisons. At least, until we have some feedback from users.
I will also try this on a few real-life projects and check for any edge cases.

We also need to support normal functions, not just arrow functions, so I would add a test for them as well. You can use `dump_node()` and `print_node()` functions to help you working with different node types. Also this can be helpful https://getrector.com/ast.

The test is failing because Rector does not know what the `Collection->filter()` method returns. We need to supply a stub in `stubs/Illuminate/Support/Collection.php`, check how the other stubs are implemented, you can copy the `filter()` and `reject()` methods' signatures from the real class in the Laravel framework. After you implement a stub, you need `composer dump-autoload` locally and the tests should be passing. If it's unclear :sweat_smile: I can fix that part in your PR.

2024-07-22 13:54 UTC, spawnia commented
> We also need to support normal functions, not just arrow functions

I thought about this, but found that it can become really tricky. For example, what are we supposed to do if there are multiple return statements? I would leave it for now.

2024-07-30 17:35 UTC, GeniJaho requested changes

2024-07-30 17:35 UTC, GeniJaho commented on README.md
> +| [LaravelSetList::LARAVEL_ARRAYACCESS_TO_METHOD_CALL](https://github.com/driftingly/rector-laravel/blob/main/config/sets/laravel-arrayaccess-to-method-call.php)                             | Convert
Please revert the changes in the Readme regarding configuration. Keep only the reordering of the list of sets, with the new set added.

The reason is that it's a bit confusing what the level-sets do, and we need proper documentation on the differences between sets like `LaravelLevelSetList::UP_TO_LARAVEL_100` and `LaravelSetList::LARAVEL_100`. I don't think they function quite the same as the core Rector PHP level-sets, but I could be wrong.

Feel free to open another PR just with the Readme updates regarding configuration 😄.
Rest of the PR looks good, we can merge right away.

2024-07-31 07:56 UTC, spawnia commented on README.md
> +| [LaravelSetList::LARAVEL_ARRAYACCESS_TO_METHOD_CALL](https://github.com/driftingly/rector-laravel/blob/main/config/sets/laravel-arrayaccess-to-method-call.php)                             | Convert
Done, I opened https://github.com/driftingly/rector-laravel/pull/237. I think I properly documented the differences between sets there, especially given that there is no documentation about this at all right now 😉 But let's discuss this further in the new pull request.

Thanks for your feedback on this!

2024-07-31 17:07 UTC, GeniJaho approved these changes

2024-07-31 17:07 UTC, merged